config/routes.rb
CoreHotel::Application.routes.draw do
  resources :employees

  namespace "admin" do 
    root :to => "employees#index"
    resources :employees
  end

  scope '/' do
    match '/about'  	=> 'about#about', :as => :about
    match '/contact'  	=> 'about#contact', :as => :contact
    match '/services'  	=> 'about#services', :as => :services
    match '/staff'  	=> 'employees#index', :as => :staff
    match '/properties' => 'about#properties', :as => :properties
  end
  root :to => 'home#index'
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :title, :bio, :order, :avatar
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/about_controller.rb
class AboutController < ApplicationController

	def about
	end

	def properties
	end

	def contact
	end

	def services
	end

end

app/controllers/admin/employees_controller.rb
class Admin::EmployeesController < ApplicationController
  respond_to :html
  before_filter :get_employee, :except => [:index, :create]
  layout 'admin'

  def index
    @employees = Employee.all(:order => `order`)
    respond_with(@employees)
  end
  
  def show
    respond_with(@employee)
  end
  
  def new
    respond_with(@employee)
  end
  
  def edit
    respond_with(@employee)  
  end

  def update
    if @employee.update_attributes(params[:employee])
      redirect_to [:admin, @employee], notice: 'Staff was successfully updated.'
    else
      render :action => 'edit'
    end
  end

  def create
    @employee = Employee.new(params[:employee])
    if @employee.save
      redirect_to [:admin, @employee], notice: 'Staff was successfully created.'
    else
      flash[:alert] = "bummer..."
      render :action => 'new'
    end
  end
  
  def destroy
    @employee.destroy
    redirect_to admin_employees_url, :notice => "Deleted..."
  end

  private
    def get_employee
      @employee = params[:id].present? ? Employee.find(params[:id]) : Employee.new
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/employee_controller.rb
class EmployeeController < ApplicationController
  respond_to :html

  def index
  	@employees = Employee.all
    respond_with(@employees)
  end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  respond_to :html

  def index
  	@employees = Employee.all(:order => `order`)
    respond_with(@employees)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	layout 'home'

	def index
	end
	

end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/about/about.html.erb
<div class="row-fluid">
	<div class="span2">
		<p class="side-text">
			Core 3 Hotel Management is dedicated to helping your hotel be a success.
		</p>
	</div>
	<div class="span10 content-container">
		<h2>About Core 3 Hotel Management</h2>
		<p>
			Core 3 Hotel Management prides itself on being a first class hotel management company. The staff at Core 3 Hotel Management has a long history with all aspects of hotel management and development. Our dedicated staff is determined to provide hotel owners with professional and courteous attention including the smallest of details. We realize a hotel is major investment and we at Core 3 Hotel Management are here to help make your ownership experience enjoyable and profitable.
		</p>
		<p>
			Our philosophy is that every hotel deserves individualized attention and that no two are alike. Core 3 Hotel Management knows that providing quick results is very important. We rely heavily on revenue management practices, accountability from our sales staff and periodically observing all expenses to provide a better bottom line for ownership. We utilize a “hands on” approach in our management style and are committed to treating all customers, owners, and staff with respect and the ability to have open communication.
		</p>
		<p>
			We appreciate the opportunity to allow us to take over the stress and daily concerns of your investment. We are committed to thorough communication including monthly statements, reports of shortcomings and “home runs” as well as monthly conference calls with the key operators of the hotel.
		</p>
	</div>
</div>

app/views/about/contact.html.erb
<div class="row">
	<div class="span10 offset2 content-container">
		<h2>Contact Us</h2>
		<ul class="locations">
			<li>
				<ul class="location-details">
					<li>
						<h3>Core 3 Hotel Management</h3>
					</li>
					<li>1716 RT Dunn Drive, Suite 4</li>
					<li>Bloomington, IL  61701</li>
					<li>Phone: 309-808-2125</li>
					<li>Email: <a href="mailto:info@core3hm.com">info@core3hm.com</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>

app/views/about/index.html.erb
<img src="http://placehold.it/957x180" alt="">
<div class="row-fluid">
	<div class="span2">
		 	<p style="padding: 15px;">
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh arcu, egestas ut tincidunt sed, laoreet rutrum justo. Pellentesque ornare, est vel pharetra tincidunt, massa diam mattis justo, id ultrices diam justo in sem. Etiam eget risus lorem.</p>
	</div>
	<div class="span10">
		<h2>About Core 3 Stuff</h2><p>
		Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh arcu, egestas ut tincidunt sed, laoreet rutrum justo. Pellentesque ornare, est vel pharetra tincidunt, massa diam mattis justo, id ultrices diam justo in sem. Etiam eget risus lorem. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam erat volutpat. Vivamus eu ligula nibh, eget lacinia felis. Sed vitae orci sed enim commodo vulputate in in tortor.
</p><p>
Etiam fermentum commodo massa, eget tempor urna hendrerit nec. Cras id venenatis leo. In bibendum dui orci, sed pulvinar quam. In orci libero, interdum a consequat et, convallis quis ligula. Aenean eu metus non elit molestie porttitor. Mauris tempus vehicula condimentum. Suspendisse sem sapien, luctus quis convallis at, dapibus sit amet tortor. Nullam commodo, leo vitae facilisis luctus, enim elit ultrices mauris, et luctus odio tellus id leo. Pellentesque ullamcorper molestie auctor. Nullam fringilla dolor ultricies sem tristique feugiat.</p>
</div>
</div>

app/views/about/properties.html.erb
<div class="row-fluid">
	<div class="span2">
		<p class="side-text">
			Holiday Inn Bloomington recently earned 2012 Certificate of Excellence award from Tripadvisor.
		</p>
	</div>
	<div class="span10 content-container">
		<h2>Properties</h2>
		<ul id="hotel-list">
			<li class="hotel">
				<h3>Holiday Inn Hotel and Suites Bloomington Airport</h3>
				<ul class="address">
					<li>3203 East Empire</li>
					<li>Bloomington IL 61704</li>
					<li>
						<a href="http://www.holidayinn.com/hotels/us/en/bloomington/bmiil/hoteldetail">View More Information</a>
					</li>
				</ul>
				<h4>Hotel Specifications</h4>
				<ul>
					<li>126 Guest Rooms</li>
					<li>5000 SF of meeting space</li>
				</ul>
				<h4>Amenities</h4>
				<ul>
					<li>Business Center</li>
					<li>Health and Fitness Center</li>
					<li>Spa</li>
					<li>High Speed Internet</li>
				</ul>
				<h4>Dining</h4>
				<ul>
					<li>Baxter’s American Grille</li>
				</ul>
			</li>
		</ul>
	</div>
</div>

app/views/about/services.html.erb
<div class="row-fluid">
	<div class="span2">
		<p class="side-text">
			Core 3 Hotel Management offers a variety of services that can be tailored
to fit your needs.
		</p>
	</div>
	<div class="span10 content-container">
		<h2>Management Services</h2>
		<p>
			At Core 3 Hotel Management we believe that each property requires individualized attention. We feel that there is not a “one size fits all” approach to management. We offer a variety of management services to fit the needs of each hotel owner.
		</p>
		<h4>Full Service Management</h4>
		<p>
			We offer full service hotel management, which encompasses everything required to manage and run a hotel on a daily basis while exceeding guest expectations and overall profitability for the investors. We immediately begin to implement our proven procedures and policies to successfully manage your property. We make sure that the right people are in place with the proper tools to create a notable hotel for the community and something the ownership can be proud of.
		</p>
		<h4>Accounting</h4>
		<p>
			We also offer accounting services for those properties that may not have a need for our full service management. This would include implementing practices and procedures to safe guard your investment and daily online access through our powerful web based accounting system that allows daily monitoring of the performance. We provide owners with monthly reports of which will clearly outline the success and challenges in each given category.
		</p>
		<h4>Consulting</h4>
		<p>Core 3 Hotel Management is available for consulting. We offer consulting services for overall hotel management or we can provide assistance in any particular area where your hotel may need assistance. This would include consulting of sales and marketing, training of departmental managers or General Managers, implementing training procedures and expectations for the guest service representatives or also re-vamping housekeeping. Wherever a challenge may be a concern, we can offer our suggestions or be “hands on” to implement a plan to expedite the overall positive outcome that will benefit not only your team but also the customer and ultimately the bottom line.</p>
	</div>
</div>

app/views/about/staff.html.erb
<div class="row-fluid">
	<div class="span2">
		<p class="side-text">
			Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin nibh arcu, egestas ut tincidunt sed, laoreet rutrum justo. Pellentesque ornare, est vel pharetra tincidunt, massa diam mattis justo, id ultrices diam justo in sem. Etiam eget risus lorem.
		</p>
	</div>
	<div class="span10 content-container">
		<h2>Staff</h2>
		<ul class="staff">
			<li class="person">
				<div class="row-fluid">
					<div class="span1">
						<img src="http://placehold.it/120x150" alt=""></div>
					<div class="span6">
						<ul class="person-details">
							<li>
								<h4>Mark Fetzer</h4>
							</li>
							<li>Da Boss!</li>
							<li>
								<p>
									Mr. Fetzer is responsible for overall strategic planning, organizational development, new business development, investor relations, franchise, relations and acquisitions.
								</p>
							</li>
						</ul>
					</div>
				</div>
			</li>
			<li class="person">
				<div class="row-fluid">
					<div class="span1">
						<img src="http://placehold.it/120x150" alt=""></div>
					<div class="span6">
						<ul class="person-details">
							<li>
								<h4>Mark Fetzer</h4>
							</li>
							<li>Da Boss!</li>
							<li>
								<p>
									Mr. Fetzer is responsible for overall strategic planning, organizational development, new business development, investor relations, franchise, relations and acquisitions.
								</p>
							</li>
						</ul>
					</div>
				</div>
			</li>

		</ul>
	</div>
</div>

app/views/admin/employees/_form.html.erb
<%= form_for [:admin, @employee], :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :bio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :bio, :class => 'text_area' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :avatar, :class => 'control-label' %>
    <div class="controls">
     <%= f.file_field :avatar, :class => 'file_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :order, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :order, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                employees_path, :class => 'btn' %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<%- model_class = @employee.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/admin/employees/index.html.erb
<%- model_class = Employee.new.class -%>
<h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:avatar) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:bio) %></th>
      <th><%= model_class.human_attribute_name(:order) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= image_tag employee.avatar_url(:thumb) if employee.avatar? %></td>
        <td><%= employee.name %></td>
        <td><%= employee.title %></td>
        <td><%= employee.bio %></td>
        <td><%= employee.order %></td>
        <td><%= employee.created_at.strftime("%b %d, %Y") %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_admin_employee_path(employee), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      admin_employee_path(employee),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_admin_employee_path,
            :class => 'btn btn-primary' %>

app/views/admin/employees/new.html.erb
<%- model_class = @employee.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               	:default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/admin/employees/show.html.erb
<%- model_class = @employee.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @employee.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @employee.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bio) %>:</strong></dt>
  <dd><%= @employee.bio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:order) %>:</strong></dt>
  <dd><%= @employee.order %></dd>
  <dt><strong><%= model_class.human_attribute_name(:avatar) %>:</strong></dt>
  <dd><%= @employee.avatar %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              admin_employees_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_admin_employee_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              admin_employee_path(@post),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/employees/index.html.erb
<div class="row-fluid">
	<div class="span2">
		<p class="side-text">
			Core 3 Hotel Management’s staff takes pride in each hotel they manage.
		</p>
	</div>
	<div class="span10 content-container">
		<h2>Staff</h2>
		<ul class="staff">
		<% @employees.each do |employee| %>
			<li class="person">
				<div class="row-fluid">
					<div class="span1">
						<% if employee.avatar? %>
							image_tag employee.avatar_url(:thumb) 
						<% else %>
							<img src="http://placehold.it/120x150" alt="">
						<% end %>
					</div>
					<div class="span8">
						<ul class="person-details">
							<li>		
								<h4>
									<%= employee.name %>
								</h4>
							</li>
							<li>
								<label class="title">
								 <em><%= employee.title %></em>
								</label>
							</li>
							<li>
								<p>
									<%= employee.bio %>
								</p>
							</li>
						</ul>
					</div>
				</div>
			</li>
		<% end %>
		</ul>
	</div>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Core 3 Hotel Management</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>



  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">Core 3 Hotel Management</a>
    <div class="nav-collapse">
      <ul class="nav">
        <li><%= link_to "Properties", properties_url %></li>
        <li><%= link_to "Management Services", services_url %></li>
        <li><%= link_to "About Us - Philosophy", about_url %></li>
        <li><%= link_to "Staff Bios", staff_url %></li>
        <li><%= link_to "Contact Us", contact_url %></li>
      </ul>
    </div>
      </div>
    </div>
  </div>
  
  
<div class="container" style="padding-top: 20px;">
  <%= yield %>
</div>

  
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Core 3 Hotel Management</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">

  </style>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Hotel Management located in Bloomington, IL">
  <meta name="keywords" content="Hotel, Management, Bloomington, IL, Property">

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32460653-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>

</head>
<body>
  <%= image_tag("background/bmi-il-hi-interior-05.jpg", :border => 0, :class => "bg" ) %>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">Core 3 Hotel Management</a>
        <div class="nav-collapse">
          <ul class="nav">
            <li><%= link_to "Properties", properties_url %></li>
            <li><%= link_to "Management Services", services_url %></li>
            <li><%= link_to "About Us - Philosophy", about_url %></li>
            <li><%= link_to "Staff Bios", staff_url %></li>
            <li><%= link_to "Contact Us", contact_url %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container main-content">
    <div class="header-logo">
      <%= image_tag("logos/H-mgmt-BandW.png", :border => 0, :class => "header-logo" ) %>
    </div>
      <%= image_tag("sub-headers/bmi-il-hi-interior-0" + (1 + rand(4)).to_s() + ".jpg", :border => 0, :class => "sub-header-logo" ) %>

      <%= yield %>  
    <div class="footer">
      <p>
        <a href="http://www.core3hotelmanagement.com">Core 3 hotel Management</a> is a division of <a href="http://www.core3pm.com">Core 3 Property Management</a>. Core 3 Property Management’s mission is to stand above the competition by providing quality property management in an honest and professional manner to ensure long-lasting relationships with clients and property owners.
      </p>
    </div>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Core 3 Hotel Management</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="Hotel Management located in Bloomington, IL">
  <meta name="keywords" content="Hotel, Management, Bloomington, IL, Property">
  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-32460653-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</head>
<body>

<script type="text/javascript">
  $(function() {
    $('.carousel').carousel({
      interval: 10000,
      pause: ""
    });
  })
</script>
<style type="text/css">
  body { overflow: hidden; }
  #myCarousel img { width:100%; height: 100%; }
  #footer
</style>
<div id="myCarousel" class="carousel slide" style="position:absolute; top: 0; z-index:-1; height:100%; width:100%;">
  <div class="carousel-inner">
    <div class="active item">
      <%= image_tag("properties/bmi/exterior/bmi-il-hi-exterior-night.jpg", :border => 0 ) %> 
    </div>
    <div class="item">
      <%= image_tag("properties/bmi/exterior/bmi-il-hi-exterior-day.jpg", :border => 0 ) %> 
    </div>
    
  </div>
</div>
  <div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container">
        <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </a>
        <a class="brand" href="<%= root_url %>">Core 3 Hotel Management</a>
    <div class="nav-collapse">
      <ul class="nav">
        <li><%= link_to "Properties", properties_url %></li>
        <li><%= link_to "Management Services", services_url %></li>
        <li><%= link_to "About Us - Philosophy", about_url %></li>
        <li><%= link_to "Staff Bios", staff_url %></li>
        <li><%= link_to "Contact Us", contact_url %></li>
      </ul>
    </div>
      </div>
    </div>
  </div>
  
  <div id="header" style="background-color: #fff; padding-left: 10px;" >
    <div style="width: 957px; margin: 0px auto; ">
      <%= image_tag("logos/H-mgmt-BandW.png", :border => 0) %> 
    </div>
  </div>

  <%= yield %>

  <div id="footer" style="position: absolute; bottom:0; width:100%; border-top: 2px solid #1B2B32;">
    <div style="padding: 10px; text-align: center; margin: 0 auto; background-color: #242424; color: #fff;">
      <p>© 2012 Core 3 Hotel Management. All Rights Reserved</p>
    </div>
  </div>
  
  
</body>
</html>

app/views/posts/show.html.erb
<%- model_class = @post.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @post.description %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_post_path(@post), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              post_path(@post),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>